version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata: